@startuml
title Component Diagram: Each component as a folder
package Managers {
    component GameManager
    component LevelManager [
        LevelManager APIs:
        - Next, Replay
        - Win, Lose
        - Init player
    ]
    component DataManager [
        DataManager APIs:
        - Store, load user data
        - Game data (obstacles data)
    ]
    component ObstacleManager [
        ObstacleManager APIs:
        - Init obstacles, traps
    ]
    component UIManager [
        UIManager APIs:
        - Init UI
        - Main, Level UI
    ]
    component AdsManager [
        AdsManager APIs:
        - Init Ads
        - Banner, Reward, Interstitial
    ]
    component AudioManager
}
note left of Managers
    All managers will 
    not be destroyed in 
    lifetime of the game
end note

package Controllers {
    package UI {
        component MainController
        component LevelController
    }

    package Gameplay {
        component PlayerController [
            PlayerController:
            - Control input
            - Check alive/die
        ]
        component ObstacleController
    }
}

Managers --> Controllers
@enduml